### ISSUE TITLE
Support creating Flutter docs sample applications

### ISSUE THREAD

**Issue by DanTup** [Dart-Code/Dart-Code#1356]
Equiv of these:
https://github.com/flutter/flutter/issues/25461
https://github.com/flutter/flutter-intellij/issues/2968

There are a few parts to this:

- [x] #1359 Support creating flutter samples from a command palette command
- [x] #1360 Support creating Flutter sample code apps from URLs
- [ ] #1361 Support creating Flutter sample apps from hover documentation

**Comment by DanTup** [comment]
There's only one thing left to do here (https://github.com/Dart-Code/Dart-Code/issues/1361) but it won't be in the next release because it's blocked by VS Code and even if they fixed it today, it wouldn't ship until after us.

So for v2.22 this feature will be available only in the command palette (and via external URIs if we choose to put buttons for them anywhere). v2.23 will hopefully have links in the hovers.
