### ISSUE TITLE
Add support to SDK DAPs for recent Dart-Code DAP features

### ISSUE THREAD

**Issue by DanTup** [Dart-Code/Dart-Code#3690]
- [x] Dart: `customTool`/`customToolReplacesArgs` (#3656)
  https://dart-review.googlesource.com/c/sdk/+/221625
- [x] Flutter: `customTool`/`customToolReplacesArgs` (#3656)
  https://github.com/flutter/flutter/pull/94475
- [x] `vmAdditionalArgs` (#3685) that allows args between `dart` and `run test:test` in test runs
  https://dart-review.googlesource.com/c/sdk/+/221800
