### ISSUE TITLE
Support multi-root workspaces

### ISSUE THREAD

**Issue by DanTup** [Dart-Code/Dart-Code#453]
https://github.com/Microsoft/vscode/wiki/Extension-Authoring:-Adopting-Multi-Root-Workspace-APIs

Adopting multi-root support in VS Code looks more complicated than expected, not because of technical work but questions about how things should work. We might be able to take ideas from other IDEs for some of these, though I don't know if they have the same sort of multi-root support that Code does.

# Migrating off rootPath

## SDK Paths, Flutter/Fuchsia Project Detection

Currently we have some flags that say whether we're a Flutter/Fuchsia project and we use them to influence the search paths for SDKs. With multi-roots, we might have a Flutter and a standard Dart project loaded (or even multiple of each). Since Fuchsia comes with both Flutter and Dart, and Flutter comes with Dart, we'll simply search for project types in that order (Fuchsia -> Flutter -> Dart) and use all the SDKs from the first one for all projects.

Any code currently checking `isFlutterProject` etc. will use a new `ProjectType` enum. Because of the order above, we will assume any workspace that contains any Fuchsia to be a Fuchsia project, and any non-Fuchsia project that contains any Flutter to be a Flutter project (otherwise, everything is a Dart project).

### Tasks

- [x] Simplify SDK detection (#440)
- [x] Support scanning all projects for the most appropriate SDK type
- [x] Update anywhere using isFlutterProject/isFuchsiaProject to use new ProjectType setting

## Analysis Server Package Roots

Normally we set the package root to just be the workspace root and let the analysis server deal with things. However we currently have a workaround for the flutter repo (https://github.com/Dart-Code/Dart-Code/issues/275) which means we have to set multiple roots.

It's possible for workspace folders to overlap (eg. one is a parent of another) so we should probably also either ensure the analysis server handles this nicely, or be sure to strip and folders that are children of another folder).

### Tasks

- [x] Decision: To migrate off `rootPath` here, just perform the above logic for each workspace folder and merge the results into a single big array
- [x] Migrate analysis server roots off `rootPath` to use above logic
- ~~Ensure we only send workspace roots that look like Dart projects - it's now valid for our extension to be loaded alongside a non-Dart project and we don't want to tell the analysis server to start analysing other projects~~ moved to #466
- [x] Handle events for adding/removing workspace folders to re-set the analysis roots and perform any required cleanup (eg. removing errors from folders that are removed)
- ~~Handle when a workspace folder becomes/ceases to be a Dart project~~ moved to #466
- [x] Ensure overlapping folders work as expected

## Reanalyse

There are some places that force a reanalyse - currently they also assume `rootPath` is valid to send. We should extract some logic to avoid duplicating the above logic in these places too.

### Tasks

- [x] Extract analysis roots so we don't need to recalculate them for reanalyse

## Dependency Tree

We currently render the dependency tree in the explorer but this assumes a single project. Possible options:

- Add parent root notes for each workspace folder
- Only show the tree when a file is selected/open and render it for that workspace folder (I think this wouldn't be a good experience)
- Remove the tree - is it all that useful?

### Tasks

- [x] Decide how to handle this
- [x] Implement it (#465)
- [x] Possibly we already don't handle this well for folders with multiple projects in child folders (#464)

## isWithinRootPath

There's a bunch of places where we check whether a file is within the root path - this is usually to see whether it's valid to analyse or use to find the project root. This should be simple to implement as "is within any workspace folder".

### Tasks

- [x] Rename and refactor to check all workspace folders

## Workspace symbol display path

We display relative paths in the workspace symbol provide. We should change this to use a relative path to whichever workspace folder is most appropriate (probably we can assume `workspace.getWorkspaceFolder` does the right thing here, but we should test with overlapping folders).

### Tasks

- [x] Refactor display path to be relative to an appropriate workspace folder
- [x] Ensure this behaves reasonable for overlapping workspace folders

## Root Paths for SDK Commands

We currently allow running SDK commands in the root. When you have multiple projects open we'll need to prompt the user for which workspace folder to use with `showWorkspaceFolderPick`.

### Tasks

- [x] Call `showWorkspaceFolderPick` to get a root path before invoking SDK commands

# Settings Changes

With multi-root workspaces, we need to decide which settings are allowed to be applied at a resources level (which are valid in a given folders `settings.json`) and which must be applied at the window level (in the global `settings.json` or the workspace file).

By default, everything is `window` which means the settings applied at a folder level will no longer work when you "upgrade" to a workspace.

We should try to support as many settings at the resource level as possible, updating the config wrapper to only allow you to read them by providing a resource url. #457 has been opened for this work.

- [x] Add support for reading config for a uri (in a strongly-typed wrapped way, like existing config)
- [x] Ensure config options can only be read from the correct config (global vs resource)
- [x] Migrate all appropriate settings to resource-level (#457, #461)
- [x] Make SDK-switcher work at Workspace (new workspace, not old workspace = folder) level
