### ISSUE TITLE
Flutter Outline

### ISSUE THREAD

**Issue by DanTup** [Dart-Code/Dart-Code#605]
This case is to implement something similar to the Flutter Outline view from IntelliJ (note: this is still heavily in dev, using an experimental API and subject to change!)

![flutter outline in intellij](https://user-images.githubusercontent.com/1078012/37085186-4a0f81be-21ec-11e8-97d9-f7f9f20a1db6.png)

- [x] Implement basic tree
- [x] Navigate to code on selection
- [x] Stop outline refactor commands appearing in the palette
- [ ] Refactors on context menu (https://github.com/dart-lang/sdk/issues/32462)
- [x] Widget (Flutter) icons
- [x] Tree nodes collapse when performing refactor
- [x] Tooltips
- [x] Add a preview flag
- [x] Sorting of context menu is bad
- [x] Require 1.20 analysis server
- [x] Update to new ranges provided by server 1.20
- [x] Stale data renders while waiting for updated data when switching file
- [ ] Highlight code for selected item (https://github.com/Microsoft/vscode/issues/45059)
- [x] Position code on screen better (https://github.com/Microsoft/vscode/issues/45742)
- [x] Reveal tree node as navigating code
- [x] Clicking out of editor (eg into debug output) shouldn't hide Outline (https://github.com/Microsoft/vscode/issues/45188)
- [ ] Set unique IDs per node (globally unique) so updating code/running refactor keeps correct item selected
- [x] Don't collapse nodes on clicking (https://github.com/Microsoft/vscode/issues/34130)
- [x] Show outline above deps (https://github.com/Microsoft/vscode/issues/45053)
- [x] Tree loses focus on click (so can't navigate with keyboard)
- [x] Method/field icons? (https://github.com/Microsoft/vscode/issues/45057)
- [x] Move to its own sidebar icon
- [x] Remove `enableProposedApi`
- [ ] Doesn't unselect node when you move out of all elements (https://github.com/microsoft/vscode/issues/48754)

**Comment by chances** [comment]
What does this issue cover?

**Comment by DanTup** [comment]
Apologies, I thought I'd replied to this! This case is to add something like the Flutter Outline view that was added to IntelliJ recently:

https://groups.google.com/forum/#!topic/flutter-dev/lKtTQ-45kc4

**Comment by sionicion** [comment]
What's the current status on this? Is there a way to test the current state of it?

**Comment by DanTup** [comment]
There's been no real progress on this. Periodically I come back to it, rebase the changes I have and test them out, but each time I'm disappointed with the behaviour. There are two possible implementations but both of them have significant issues that aren't resolved.

1. A completely custom tree - this doesn't work well becaues custom trees have lots of quirks and missing features compared to the built-in Outline view
2. Use the built-in Outline view with a setting to enable the Flutter parts - this doesn't work well because injecting the extra nodes messes up the symbol list (which is the same issue as https://github.com/microsoft/vscode/issues/51332)

I think the second option is best, but unless Code gets a fix for the issue above, it's not really a good option.
