### ISSUE TITLE
Display Flutter test results in a tree

### ISSUE THREAD

**Issue by DanTup** [Dart-Code/Dart-Code#980]
- [x] Clicking tests goes to wrong location/doesn't navigate https://github.com/flutter/flutter/issues/18195
- [ ] Clicking suite/group icons always collapses/expands https://github.com/Microsoft/vscode/issues/34130
- [x] Show single test output when clicking on nodes
- [x] Remove timeout workaround for revealing nodes and requires vNext of Code
- [ ] Running a single test causes other test results for that suite to vanish https://github.com/dart-lang/test/issues/837

Non-Flutter tests are in their own issue (#87) because they're more complicated due to https://github.com/dart-lang/test/issues/838

**Comment by DanTup** [comment]
I've got the basics working... When you run a flutter test script, we now route the results into a tree. I've also added a `Run All Tests` command that'll run them all in concurrent debug sessions (since `flutter test` doesn't support more than one at a time), though we may need to limit how many of these run at the same time.

This really needs some good feedback from people that have real Flutter tests, so if anyone wants to test this please ping me and I'll sort a build out (I can't easily ship this behind a flag because it moves a lot of code from the debug adapter into the editor). Ping @mit-mit @devoncarew @xster @escamoteur @Skylled!

There are some weird limitations/quirks (many due to VS Code), which I'll try to keep in a list maintained at the top of this issue.

![test_demo 1](https://user-images.githubusercontent.com/1078012/40982225-a0763bae-68d4-11e8-957e-dab39a98b6e6.gif)

**Comment by DanTup** [comment]
Wow, Chrome doesn't like 4MB GIFs 😨

**Comment by DanTup** [comment]
This is merged into master. The outstanding issues mentioned above are likely to take a while to be fixed in their respective places, but I'll update when they are.
